steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/crypto-plexus-409304/nc-dashboard', '.']

  # Step 2: Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/crypto-plexus-409304/nc-dashboard']

  # Step 3: Deploy the container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'nc-dashboard',           # Cloud Run service name
      '--image', 'gcr.io/crypto-plexus-409304/nc-dashboard',  # Image from Step 2
      '--platform', 'managed',
      '--region', 'us-central1',                 # Change to your desired region
      '--allow-unauthenticated'                  # Public access
    ]

# Specify the images that are built
images:
  - 'gcr.io/crypto-plexus-409304/nc-dashboard'